name: Machine Learning Retraining and Docker CI

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        cache: 'pip'

    - name: Install Core Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy

    - - name: Run MLflow Project Retraining
      run: |
        # 1. Run the MLflow retraining pipeline
        mlflow run MLProject/ --entry-point main --no-conda
        
        # 2. Corrected python parsing script using .loc[] instead of .iloc[]
        RUN_ID=$(python -c "import mlflow; df=mlflow.search_runs(experiment_names=['Housing_Prices_Retraining_CI']); print(df.loc[0, 'run_id'])")
        
        # 3. Save the clean string into the GitHub Environment variable
        echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image via MLflow
      run: |
        mlflow models build-docker -m "runs:/${{ env.MLFLOW_RUN_ID }}/model" -n "urashia/workflow-ci:latest"
        docker push urashia/workflow-ci:latest
